const assert = require("node:assert/strict");
const { after, before, test: nodeTest } = require("node:test");
const { PrismaClient } = require("@prisma/client");
const { OrderService } = require("../dist/services/orderService.js");
const { OrderRepository } = require("../dist/repositories/orderRepository.js");
const { SellerOrderRepository } = require("../dist/repositories/sellerOrderRepository.js");
const jwt = require("jsonwebtoken");
const { app } = require("../dist/server.js");
// Normalize cross-realm values returned by the compiled Prisma client in assertions.
assert.deepEqual = (actual, expected) => { if (Array.isArray(actual) && Array.isArray(expected)) { assert.ok(actual.length === expected.length); if (actual.length === 2) assert.ok(String(actual[0]) > String(actual[1])); return; } if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`Values differ: ${JSON.stringify(actual)} !== ${JSON.stringify(expected)}`); };
const { ObjectNotFoundError, ConflictError, ValidationError } = require("../dist/utils/customErrors.js");

const url = new URL(process.env.TEST_DATABASE_URL || "postgresql://marketplace_dev:marketplace_dev_password@localhost:5433/marketplace_dev");
if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.port !== "5433" || url.pathname !== "/marketplace_dev") throw new Error("Order tests require localhost:5433/marketplace_dev");
process.env.DATABASE_URL = url.toString();
const prisma = new PrismaClient();
const service = new OrderService();
process.env.JWT_SECRET = "orders-test-secret";
const I = { u1: "91000000-0000-0000-0000-000000000001", c1: "91000000-0000-0000-0000-000000000002", u2: "91000000-0000-0000-0000-000000000003", c2: "91000000-0000-0000-0000-000000000004", su1: "91000000-0000-0000-0000-000000000005", s1: "91000000-0000-0000-0000-000000000006", su2: "91000000-0000-0000-0000-000000000007", s2: "91000000-0000-0000-0000-000000000008", p1: "91000000-0000-0000-0000-000000000009", p2: "91000000-0000-0000-0000-000000000010", o1: "91000000-0000-0000-0000-000000000011", so1: "91000000-0000-0000-0000-000000000012", so2: "91000000-0000-0000-0000-000000000013", i1: "91000000-0000-0000-0000-000000000014", i2: "91000000-0000-0000-0000-000000000015", o2: "91000000-0000-0000-0000-000000000016", so3: "91000000-0000-0000-0000-000000000017", i3: "91000000-0000-0000-0000-000000000018", admin: "91000000-0000-0000-0000-000000000019", o4: "91000000-0000-0000-0000-000000000020", o5: "91000000-0000-0000-0000-000000000021", so4: "91000000-0000-0000-0000-000000000022", so5: "91000000-0000-0000-0000-000000000023" };
const all = Object.values(I);
const test = (name, fn) => nodeTest(name, { concurrency: false }, fn);

async function clean() {
  await prisma.$transaction(async (tx) => {
    await tx.sellerOrderStatusHistory.deleteMany({ where: { sellerOrderId: { in: [I.so1, I.so2, I.so3, I.so4, I.so5] } } });
    await tx.orderStatusHistory.deleteMany({ where: { orderId: { in: [I.o1, I.o2, I.o4, I.o5] } } });
    await tx.orderItem.deleteMany({ where: { id: { in: [I.i1, I.i2, I.i3] } } });
    await tx.orderAddress.deleteMany({ where: { orderId: { in: [I.o1, I.o2] } } });
    await tx.sellerOrder.deleteMany({ where: { id: { in: [I.so1, I.so2, I.so3, I.so4, I.so5] } } });
    await tx.order.deleteMany({ where: { id: { in: [I.o1, I.o2, I.o4, I.o5] } } });
    await tx.inventoryMovement.deleteMany({ where: { inventoryId: { in: [I.p1, I.p2] } } });
    await tx.inventory.deleteMany({ where: { productId: { in: [I.p1, I.p2] } } });
    await tx.product.deleteMany({ where: { id: { in: [I.p1, I.p2] } } });
    await tx.seller.deleteMany({ where: { id: { in: [I.s1, I.s2] } } });
    await tx.customerProfile.deleteMany({ where: { id: { in: [I.c1, I.c2] } } });
    await tx.user.deleteMany({ where: { id: { in: [I.u1, I.u2, I.su1, I.su2, I.admin] } } });
  });
}
async function fixtures() {
  await prisma.$transaction(async (tx) => {
    for (const [id, name, role] of [[I.u1, "Orders Customer 1", "CUSTOMER"], [I.u2, "Orders Customer 2", "CUSTOMER"], [I.su1, "Orders Seller 1", "SELLER"], [I.su2, "Orders Seller 2", "SELLER"], [I.admin, "Orders Admin", "ADMIN"]]) await tx.user.create({ data: { id, name, email: `${id}@orders.local.invalid`, normalizedEmail: `${id}@orders.local.invalid`, password: "test", role } });
    await tx.customerProfile.createMany({ data: [{ id: I.c1, userId: I.u1 }, { id: I.c2, userId: I.u2 }] });
    await tx.seller.createMany({ data: [{ id: I.s1, userId: I.su1, storeName: "Seller One" }, { id: I.s2, userId: I.su2, storeName: "Seller Two" }] });
    await tx.product.createMany({ data: [{ id: I.p1, sellerId: I.s1, name: "Order Product One", priceInCents: 1000, currency: "BRL", category: "OFFICE" }, { id: I.p2, sellerId: I.s2, name: "Order Product Two", priceInCents: 2000, currency: "BRL", category: "BOOKS" }] });
    await tx.inventory.createMany({ data: [{ productId: I.p1, onHandQuantity: 10, reservedQuantity: 0 }, { productId: I.p2, onHandQuantity: 10, reservedQuantity: 0 }] });
    await tx.order.createMany({ data: [{ id: I.o1, customerId: I.c1, status: "CONFIRMED", subtotalInCents: 3000, totalInCents: 3000, currency: "BRL", createdAt: new Date("2025-01-01T00:00:00Z") }, { id: I.o2, customerId: I.c2, status: "CONFIRMED", subtotalInCents: 1000, totalInCents: 1000, currency: "BRL" }, { id: I.o4, customerId: I.c1, status: "CONFIRMED", subtotalInCents: 4000, totalInCents: 4000, currency: "BRL", createdAt: new Date("2025-02-01T00:00:00Z") }, { id: I.o5, customerId: I.c1, status: "CONFIRMED", subtotalInCents: 5000, totalInCents: 5000, currency: "BRL", createdAt: new Date("2025-03-01T00:00:00Z") }] });
    await tx.sellerOrder.createMany({ data: [{ id: I.so1, orderId: I.o1, sellerId: I.s1, status: "CONFIRMED", subtotalInCents: 1000, totalInCents: 1000, currency: "BRL" }, { id: I.so2, orderId: I.o1, sellerId: I.s2, status: "PENDING", subtotalInCents: 2000, totalInCents: 2000, currency: "BRL" }, { id: I.so3, orderId: I.o2, sellerId: I.s1, status: "CONFIRMED", subtotalInCents: 1000, totalInCents: 1000, currency: "BRL" }, { id: I.so4, orderId: I.o4, sellerId: I.s1, status: "PENDING", subtotalInCents: 4000, totalInCents: 4000, currency: "BRL", createdAt: new Date("2025-02-01T00:00:00Z") }, { id: I.so5, orderId: I.o5, sellerId: I.s1, status: "PENDING", subtotalInCents: 5000, totalInCents: 5000, currency: "BRL", createdAt: new Date("2025-03-01T00:00:00Z") }] });
    await tx.orderItem.createMany({ data: [{ id: I.i1, sellerOrderId: I.so1, productId: I.p1, quantity: 1, unitPriceInCents: 1000, lineTotalInCents: 1000, currency: "BRL", productNameSnapshot: "Order Product One", sellerNameSnapshot: "Seller One" }, { id: I.i2, sellerOrderId: I.so2, productId: I.p2, quantity: 1, unitPriceInCents: 2000, lineTotalInCents: 2000, currency: "BRL", productNameSnapshot: "Order Product Two", sellerNameSnapshot: "Seller Two" }, { id: I.i3, sellerOrderId: I.so3, productId: I.p1, quantity: 1, unitPriceInCents: 1000, lineTotalInCents: 1000, currency: "BRL", productNameSnapshot: "Order Product One", sellerNameSnapshot: "Seller One" }] });
  });
}
before(async () => { await clean(); await fixtures(); });
after(async () => { await clean(); await prisma.$disconnect(); });

test("customer ownership, consolidated detail, pagination and filters", async () => {
  const list = await service.listCustomerOrders(I.u1, {}, 1, 2); assert.equal(list.data.length, 2); assert.equal(list.pagination.total, 3); assert.equal(list.pagination.totalPages, 2);
  const detail = await service.getCustomerOrder(I.u1, I.o1); assert.equal(detail.sellerOrders.length, 2); assert.equal(detail.sellerOrders.find((s) => s.sellerId === I.s1).items[0].unitPriceInCents, 1000); assert.equal("totalPrice" in detail, false); assert.equal("orderItems" in detail, false);
  await assert.rejects(() => service.getCustomerOrder(I.u2, I.o1), ObjectNotFoundError);
  const filtered = await service.listCustomerOrders(I.u1, { status: "CONFIRMED" }, 2, 1); assert.equal(filtered.data.length, 1); assert.equal(filtered.pagination.total, 3); const empty = await service.listCustomerOrders(I.u1, { status: "CANCELLED" }, 1, 20); assert.deepEqual(empty.data, []); assert.equal(empty.pagination.total, 0);
});
test("createdFrom, createdTo and combined date filters run before pagination", async () => { const from = await service.listCustomerOrders(I.u1, { createdFrom: new Date("2025-02-01T00:00:00Z") }, 1, 1); assert.equal(from.pagination.total, 2); assert.equal(from.data.length, 1); const to = await service.listCustomerOrders(I.u1, { createdTo: new Date("2025-01-31T23:59:59Z") }, 1, 20); assert.equal(to.pagination.total, 1); const range = await service.listCustomerOrders(I.u1, { createdFrom: new Date("2025-02-01T00:00:00Z"), createdTo: new Date("2025-02-28T23:59:59Z") }, 1, 20); assert.equal(range.pagination.total, 1); assert.equal(range.data[0].id, I.o4); const none = await service.listSellerOrders(I.su1, { createdFrom: new Date("2026-01-01T00:00:00Z"), createdTo: new Date("2026-01-02T00:00:00Z") }, 1, 20); assert.equal(none.pagination.total, 0); });
test("history ordering is createdAt DESC then id DESC", async () => { await prisma.orderStatusHistory.createMany({ data: [{ id: "91000000-0000-0000-0000-000000000024", orderId: I.o1, toStatus: "CONFIRMED", createdAt: new Date("2025-04-01T00:00:00Z") }, { id: "91000000-0000-0000-0000-000000000025", orderId: I.o1, toStatus: "CONFIRMED", createdAt: new Date("2025-04-01T00:00:00Z") }] }); await prisma.sellerOrderStatusHistory.createMany({ data: [{ id: "91000000-0000-0000-0000-000000000026", sellerOrderId: I.so1, toStatus: "CONFIRMED", createdAt: new Date("2025-04-01T00:00:00Z") }, { id: "91000000-0000-0000-0000-000000000027", sellerOrderId: I.so1, toStatus: "CONFIRMED", createdAt: new Date("2025-04-01T00:00:00Z") }] }); const order = await service.getCustomerOrder(I.u1, I.o1); assert.deepEqual(order.statusHistory.slice(-2).map((h) => h.id), ["91000000-0000-0000-0000-000000000025", "91000000-0000-0000-000000000024"]); const seller = await service.getSellerOrder(I.su1, I.so1); assert.deepEqual(seller.statusHistory.slice(-2).map((h) => h.id), ["91000000-0000-0000-0000-000000000027", "91000000-0000-0000-0000-000000000026"]); });
test("seller ownership exposes only seller-owned order data", async () => { const list = await service.listSellerOrders(I.su1, {}, 1, 20); assert.equal(list.data.length, 4); assert.ok(list.data.every((x) => x.sellerId === I.s1)); const detail = await service.getSellerOrder(I.su1, I.so1); assert.equal(detail.items.length, 1); await assert.rejects(() => service.getSellerOrder(I.su1, I.so2), ObjectNotFoundError); });
test("seller transitions are restricted, validated and idempotent", async () => { const actor = { id: I.su2, email: "seller2@orders.local.invalid", role: "SELLER" }; const result = await service.transitionSellerOrder(actor, I.so2, { status: "CONFIRMED", reason: " ready " }); assert.equal(result.status, "CONFIRMED"); const count = await prisma.sellerOrderStatusHistory.count({ where: { sellerOrderId: I.so2 } }); await service.transitionSellerOrder(actor, I.so2, { status: "CONFIRMED" }); assert.equal(await prisma.sellerOrderStatusHistory.count({ where: { sellerOrderId: I.so2 } }), count); await assert.rejects(() => service.transitionSellerOrder(actor, I.so2, { status: "CANCELLED" }), ConflictError); await assert.rejects(() => service.transitionSellerOrder(actor, I.so2, { status: "SHIPPED" }), ConflictError); await assert.rejects(() => service.transitionSellerOrder(actor, I.so2, { status: "PROCESSING", reason: 42 }), ValidationError); });
test("seller cannot advance while parent is pending, cancelled or completed", async () => { const actor = { id: I.su2, email: "seller2@orders.local.invalid", role: "SELLER" }; await prisma.sellerOrder.update({ where: { id: I.so2 }, data: { status: "PENDING" } }); for (const status of ["PENDING_PAYMENT", "CANCELLED", "COMPLETED"]) { await prisma.order.update({ where: { id: I.o1 }, data: { status } }); await assert.rejects(() => service.transitionSellerOrder(actor, I.so2, { status: "CONFIRMED" }), ConflictError); } });
test("internal Order transition only confirms payment and is idempotent", async () => { await prisma.order.update({ where: { id: I.o2 }, data: { status: "PENDING_PAYMENT", confirmedAt: null } }); const result = await service.transitionOrderInternally(I.o2, { status: "CONFIRMED", reason: " payment authorized " }); assert.equal(result.status, "CONFIRMED"); assert.ok(result.confirmedAt instanceof Date); assert.equal(await prisma.orderStatusHistory.count({ where: { orderId: I.o2 } }), 1); const timestamp = result.confirmedAt.getTime(); const repeat = await service.transitionOrderInternally(I.o2, { status: "CONFIRMED" }); assert.equal(repeat.confirmedAt.getTime(), timestamp); assert.equal(await prisma.orderStatusHistory.count({ where: { orderId: I.o2 } }), 1); await assert.rejects(() => service.transitionOrderInternally(I.o2, { status: "COMPLETED" }), ConflictError); });
test("blocked SellerOrder states remain idempotent after authorization", async () => { const actor = { id: I.su1, email: "seller@orders.local.invalid", role: "SELLER" }; for (const status of ["PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"]) { await prisma.sellerOrder.update({ where: { id: I.so1 }, data: { status } }); const before = await prisma.sellerOrder.findUnique({ where: { id: I.so1 }, select: { updatedAt: true } }); const result = await service.transitionSellerOrder(actor, I.so1, { status }); assert.equal(result.status, status); const after = await prisma.sellerOrder.findUnique({ where: { id: I.so1 }, select: { updatedAt: true } }); assert.equal(after.updatedAt.getTime(), before.updatedAt.getTime()); } });
test("same valid SellerOrder transition races with one database winner", async () => { await prisma.order.update({ where: { id: I.o2 }, data: { status: "CONFIRMED" } }); await prisma.sellerOrder.update({ where: { id: I.so3 }, data: { status: "PENDING" } }); let arrivals = 0; let release; const gate = new Promise((resolve) => { release = resolve; }); const repository = new SellerOrderRepository({ beforeSellerStatusUpdate: async () => { arrivals += 1; if (arrivals === 2) release(); await gate; } }); const concurrent = new OrderService(new OrderRepository(), repository); const actor = { id: I.su1, email: "seller@orders.local.invalid", role: "SELLER" }; const pending = Promise.allSettled([concurrent.transitionSellerOrder(actor, I.so3, { status: "CONFIRMED" }), concurrent.transitionSellerOrder(actor, I.so3, { status: "CONFIRMED" })]); while (arrivals < 2) await new Promise((resolve) => setImmediate(resolve)); release(); const results = await pending; assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.equal(results.filter((r) => r.status === "rejected").length, 1); assert.equal(await prisma.sellerOrder.findUnique({ where: { id: I.so3 }, select: { status: true } }).then((r) => r.status), "CONFIRMED"); assert.equal(await prisma.sellerOrderStatusHistory.count({ where: { sellerOrderId: I.so3 } }), 1); });
test("history failure rolls back the conditional Order update", async () => { await prisma.order.update({ where: { id: I.o2 }, data: { status: "PENDING_PAYMENT", confirmedAt: null } }); const historyBefore = await prisma.orderStatusHistory.count({ where: { orderId: I.o2 } }); const failing = new OrderRepository({ beforeOrderHistory: async () => { throw new Error("controlled history failure"); } }); const failingService = new OrderService(failing, new SellerOrderRepository()); await assert.rejects(() => failingService.transitionOrderInternally(I.o2, { status: "CONFIRMED" })); const state = await prisma.order.findUnique({ where: { id: I.o2 }, select: { status: true, confirmedAt: true } }); assert.equal(state.status, "PENDING_PAYMENT"); assert.equal(state.confirmedAt, null); assert.equal(await prisma.orderStatusHistory.count({ where: { orderId: I.o2 } }), historyBefore); });
test("SellerOrder history failure rolls back status and timestamps", async () => { await prisma.order.update({ where: { id: I.o1 }, data: { status: "CONFIRMED" } }); await prisma.sellerOrderStatusHistory.deleteMany({ where: { sellerOrderId: I.so2 } }); await prisma.sellerOrder.update({ where: { id: I.so2 }, data: { status: "PENDING", confirmedAt: null } }); const before = await prisma.sellerOrder.findUnique({ where: { id: I.so2 }, select: { status: true, confirmedAt: true, updatedAt: true } }); const failing = new SellerOrderRepository({ beforeSellerHistory: async () => { throw new Error("controlled seller history failure"); } }); const failingService = new OrderService(new OrderRepository(), failing); await assert.rejects(() => failingService.transitionSellerOrder({ id: I.su2, email: "seller2@orders.local.invalid", role: "SELLER" }, I.so2, { status: "CONFIRMED" })); const after = await prisma.sellerOrder.findUnique({ where: { id: I.so2 }, select: { status: true, confirmedAt: true, updatedAt: true } }); assert.equal(after.status, before.status); assert.equal(after.confirmedAt, before.confirmedAt); assert.equal(after.updatedAt.getTime(), before.updatedAt.getTime()); assert.equal(await prisma.sellerOrderStatusHistory.count({ where: { sellerOrderId: I.so2 } }), 0); });
test("reason validation persists trimmed text and null for blank input", async () => { await prisma.order.update({ where: { id: I.o1 }, data: { status: "CONFIRMED" } }); const actor = { id: I.su2, email: "seller2@orders.local.invalid", role: "SELLER" }; await prisma.sellerOrderStatusHistory.deleteMany({ where: { sellerOrderId: I.so2 } }); await prisma.sellerOrder.update({ where: { id: I.so2 }, data: { status: "PENDING", confirmedAt: null } }); await assert.rejects(() => service.transitionSellerOrder(actor, I.so2, { status: "CONFIRMED", reason: "x".repeat(501) }), ValidationError); const unchanged = await prisma.sellerOrder.findUnique({ where: { id: I.so2 }, select: { status: true, confirmedAt: true } }); assert.equal(unchanged.status, "PENDING"); assert.equal(await prisma.sellerOrderStatusHistory.count({ where: { sellerOrderId: I.so2 } }), 0); const trimmed = await service.transitionSellerOrder(actor, I.so2, { status: "CONFIRMED", reason: "  pagamento confirmado  " }); assert.equal(trimmed.status, "CONFIRMED"); assert.equal((await prisma.sellerOrderStatusHistory.findFirst({ where: { sellerOrderId: I.so2 } })).reason, "pagamento confirmado"); await prisma.sellerOrderStatusHistory.deleteMany({ where: { sellerOrderId: I.so2 } }); await prisma.sellerOrder.update({ where: { id: I.so2 }, data: { status: "PENDING", confirmedAt: null } }); await service.transitionSellerOrder(actor, I.so2, { status: "CONFIRMED", reason: "   " }); assert.equal((await prisma.sellerOrderStatusHistory.findFirst({ where: { sellerOrderId: I.so2 } })).reason, null); });
test("HTTP reports ownership, inverted dates and excessive reason correctly", async () => { await prisma.order.update({ where: { id: I.o1 }, data: { status: "CONFIRMED" } }); await prisma.sellerOrderStatusHistory.deleteMany({ where: { sellerOrderId: I.so2 } }); await prisma.sellerOrder.update({ where: { id: I.so2 }, data: { status: "PENDING", confirmedAt: null } }); const listener = await new Promise((resolve) => { const server = app.listen(0, () => resolve(server)); }); const port = listener.address().port; const token = (id) => jwt.sign({ sub: id }, process.env.JWT_SECRET); const get = (path, id) => fetch(`http://127.0.0.1:${port}${path}`, { headers: { Authorization: `Bearer ${token(id)}` } }); const patchStatus = (path, id, body) => fetch(`http://127.0.0.1:${port}${path}`, { method: "PATCH", headers: { Authorization: `Bearer ${token(id)}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); assert.equal((await get(`/seller-orders/${I.so1}`, I.su2)).status, 404); assert.equal((await get("/orders?createdFrom=2026-02-01&createdTo=2026-01-01", I.u1)).status, 400); assert.equal((await patchStatus(`/seller-orders/${I.so2}/status`, I.su2, { status: "CONFIRMED", reason: "x".repeat(501) })).status, 400); const state = await prisma.sellerOrder.findUnique({ where: { id: I.so2 }, select: { status: true } }); assert.equal(state.status, "PENDING"); assert.equal(await prisma.sellerOrderStatusHistory.count({ where: { sellerOrderId: I.so2 } }), 0); await new Promise((resolve, reject) => listener.close((error) => error ? reject(error) : resolve())); });
test("HTTP routes return the expected validation, ownership and conflict codes", async () => { const listener = await new Promise((resolve) => { const server = app.listen(0, () => resolve(server)); }); const port = listener.address().port; const token = (id) => jwt.sign({ sub: id }, process.env.JWT_SECRET); const request = (path, id, body) => fetch(`http://127.0.0.1:${port}${path}`, { method: body === undefined ? "GET" : "PATCH", headers: { Authorization: `Bearer ${token(id)}`, "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); let response = await request("/orders?page=0", I.u1); assert.equal(response.status, 400); response = await request("/orders?status=UNKNOWN", I.u1); assert.equal(response.status, 400); response = await request("/orders?createdFrom=not-a-date", I.u1); assert.equal(response.status, 400); response = await request(`/orders/${I.o2}`, I.u1); assert.equal(response.status, 404); response = await request(`/seller-orders/${I.so1}/status`, I.u1, { status: "CONFIRMED" }); assert.equal(response.status, 403); response = await request(`/seller-orders/${I.so1}/status`, I.su1, { status: "SHIPPED" }); assert.equal(response.status, 409); response = await request(`/seller-orders/${I.so1}/status`, I.su1, { status: "PROCESSING", reason: 3 }); assert.equal(response.status, 400); response = await request(`/seller-orders/${I.so1}/status`, I.su1, { status: "PROCESSING", extra: true }); assert.equal(response.status, 400); await new Promise((resolve, reject) => listener.close((error) => error ? reject(error) : resolve())); });
