const assert = require("node:assert/strict");
const { after, before, test: nodeTest } = require("node:test");
const { PrismaClient } = require("@prisma/client");
const jwt = require("jsonwebtoken");
const { PaymentService } = require("../dist/services/paymentService.js");
const { PaymentAttemptRepository } = require("../dist/repositories/paymentAttemptRepository.js");
const { DevPaymentProvider, PaymentProviderDefinitiveError, PaymentProviderUnknownResultError } = require("../dist/providers/paymentProvider.js");
const { ConflictError, ForbiddenError, ObjectNotFoundError, ValidationError } = require("../dist/utils/customErrors.js");
const { app } = require("../dist/server.js");
const url = new URL(process.env.TEST_DATABASE_URL || "postgresql://marketplace_dev:marketplace_dev_password@localhost:5433/marketplace_dev");
if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.port !== "5433" || url.pathname !== "/marketplace_dev") throw new Error("Payment tests require localhost:5433/marketplace_dev");
process.env.DATABASE_URL = url.toString(); process.env.JWT_SECRET = "payments-test-secret";
const prisma = new PrismaClient(); const test = (name, fn) => nodeTest(name, { concurrency: false }, fn);
const I = { u1: "92000000-0000-0000-0000-000000000001", c1: "92000000-0000-0000-0000-000000000002", u2: "92000000-0000-0000-0000-000000000003", c2: "92000000-0000-0000-0000-000000000004", su: "92000000-0000-0000-0000-000000000005", s: "92000000-0000-0000-0000-000000000006", o1: "92000000-0000-0000-0000-000000000007", o2: "92000000-0000-0000-0000-000000000008" };
const customer = { id: I.u1, email: "payment-customer@local.invalid", role: "CUSTOMER" }; const customer2 = { id: I.u2, email: "payment-customer2@local.invalid", role: "CUSTOMER" }; const seller = { id: I.su, email: "payment-seller@local.invalid", role: "SELLER" };
async function clean() { await prisma.$transaction(async (tx) => { await tx.paymentAttempt.deleteMany({ where: { orderId: { in: [I.o1, I.o2] } } }); await tx.orderStatusHistory.deleteMany({ where: { orderId: { in: [I.o1, I.o2] } } }); await tx.order.deleteMany({ where: { id: { in: [I.o1, I.o2] } } }); await tx.seller.deleteMany({ where: { id: I.s } }); await tx.customerProfile.deleteMany({ where: { id: { in: [I.c1, I.c2] } } }); await tx.user.deleteMany({ where: { id: { in: [I.u1, I.u2, I.su] } } }); }); }
async function fixtures() { await prisma.user.createMany({ data: [{ id: I.u1, name: "Payment Customer", email: customer.email, normalizedEmail: customer.email, password: "test", role: "CUSTOMER" }, { id: I.u2, name: "Payment Customer 2", email: customer2.email, normalizedEmail: customer2.email, password: "test", role: "CUSTOMER" }, { id: I.su, name: "Payment Seller", email: seller.email, normalizedEmail: seller.email, password: "test", role: "SELLER" }] }); await prisma.customerProfile.createMany({ data: [{ id: I.c1, userId: I.u1 }, { id: I.c2, userId: I.u2 }] }); await prisma.seller.create({ data: { id: I.s, userId: I.su, storeName: "Payment Store" } }); await prisma.order.createMany({ data: [{ id: I.o1, customerId: I.c1, status: "PENDING_PAYMENT", subtotalInCents: 1000, totalInCents: 1000, currency: "BRL" }, { id: I.o2, customerId: I.c2, status: "PENDING_PAYMENT", subtotalInCents: 1000, totalInCents: 1000, currency: "BRL" }] }); }
async function reset(orderId = I.o1) { await prisma.paymentAttempt.deleteMany({ where: { orderId } }); await prisma.orderStatusHistory.deleteMany({ where: { orderId } }); await prisma.order.update({ where: { id: orderId }, data: { status: "PENDING_PAYMENT", confirmedAt: null } }); }
async function create(amountIgnored, user = customer, orderId = I.o1, provider = new DevPaymentProvider(), repository = undefined) { return new PaymentService(repository, provider).createAttempt(user, orderId, { method: "PIX" }); }
async function authorize(id) { await new PaymentService().startProcessing(id); const stored = await prisma.paymentAttempt.findUnique({ where: { id } }); return new PaymentService().authorize(id, stored.providerReference); }
before(async () => { await clean(); await fixtures(); }); after(async () => { await clean(); await prisma.$disconnect(); });

test("attempt charges exactly the Order total and uses its currency", async () => { await reset(); const result = await create(); assert.equal(result.amountInCents, 1000); assert.equal(result.currency, "BRL"); assert.equal(result.status, "CREATED"); });
test("provider runs after the local transaction commits", async () => { await reset(); let observed; const provider = { createAttempt: async (input) => { observed = await prisma.paymentAttempt.findUnique({ where: { id: input.paymentAttemptId }, select: { status: true, providerReference: true, amountInCents: true } }); return new DevPaymentProvider().createAttempt(input); } }; const result = await create(undefined, customer, I.o1, provider); assert.deepEqual(observed, { status: "CREATED", providerReference: null, amountInCents: 1000 }); assert.ok(result.providerReference); });
test("definitive provider failure marks CREATED as FAILED and permits an integral retry", async () => { await reset(); const cause = new Error("decline detail"); const original = new PaymentProviderDefinitiveError("declined", "CARD_DECLINED", cause); const provider = { createAttempt: async () => { throw original; } }; await assert.rejects(() => create(undefined, customer, I.o1, provider), (error) => error === original && error.cause === cause); const failed = await prisma.paymentAttempt.findFirst({ where: { orderId: I.o1 }, orderBy: { createdAt: "desc" } }); assert.equal(failed.status, "FAILED"); assert.equal(failed.failureCode, "CARD_DECLINED"); assert.equal(failed.failureMessage, "Payment provider rejected the payment"); assert.ok(failed.failedAt); const retry = await create(); assert.equal(retry.amountInCents, 1000); });
test("unknown and unclassified provider errors keep CREATED blocked and can be reconciled", async () => { await reset(); const unknown = new PaymentProviderUnknownResultError("timeout", new Error("socket closed")); await assert.rejects(() => create(undefined, customer, I.o1, { createAttempt: async () => { throw unknown; } }), (error) => error === unknown && error.cause instanceof Error); let current = await prisma.paymentAttempt.findFirst({ where: { orderId: I.o1 }, orderBy: { createdAt: "desc" } }); assert.equal(current.status, "CREATED"); assert.equal(current.failedAt, null); assert.equal(current.failureCode, null); assert.equal(current.failureMessage, null); await assert.rejects(() => create(), ConflictError); const reconciled = await new PaymentService(new PaymentAttemptRepository(), new DevPaymentProvider()).provisionAttempt(current.id); current = await prisma.paymentAttempt.findUnique({ where: { id: current.id } }); assert.equal(reconciled.providerReference, current.providerReference); await reset(); const generic = new Error("unexpected provider failure"); await assert.rejects(() => create(undefined, customer, I.o1, { createAttempt: async () => { throw generic; } }), (error) => error === generic); current = await prisma.paymentAttempt.findFirst({ where: { orderId: I.o1 }, orderBy: { createdAt: "desc" } }); assert.equal(current.status, "CREATED"); assert.equal(current.failedAt, null); });
test("reference persistence failure leaves the attempt recoverable and reconciliation reuses its provider identity", async () => { await reset(); let calls = 0; const logicalCharges = new Set(); const provider = { createAttempt: async (input) => { calls += 1; logicalCharges.add(input.paymentAttemptId); return new DevPaymentProvider().createAttempt(input); } }; const firstRepository = new PaymentAttemptRepository(); const failingRepository = Object.create(firstRepository); failingRepository.setProviderReference = async () => { throw new Error("database unavailable"); }; await assert.rejects(() => create(undefined, customer, I.o1, provider, failingRepository), /database unavailable/); const pending = await prisma.paymentAttempt.findFirst({ where: { orderId: I.o1 }, orderBy: { createdAt: "desc" } }); assert.equal(pending.status, "CREATED"); const service = new PaymentService(firstRepository, provider); const recovered = await service.provisionAttempt(pending.id); assert.equal(calls, 2); assert.equal(logicalCharges.size, 1); assert.equal(recovered.providerReference, `dev_${require("crypto").createHash("sha256").update(pending.id).digest("hex").slice(0, 24)}`); const persisted = await prisma.paymentAttempt.findUnique({ where: { id: pending.id } }); assert.equal(persisted.providerReference, recovered.providerReference); });
test("amountInCents and other protected fields are rejected by HTTP", async () => { const listener = await new Promise((resolve) => { const server = app.listen(0, () => resolve(server)); }); const port = listener.address().port; const token = jwt.sign({ sub: I.u1 }, process.env.JWT_SECRET); const response = await fetch(`http://127.0.0.1:${port}/orders/${I.o1}/payment-attempts`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ method: "PIX", amountInCents: 1000 }) }); assert.equal(response.status, 400); await new Promise((resolve, reject) => listener.close((e) => e ? reject(e) : resolve())); });
test("active or captured attempts block new attempts, while failed/cancelled retries are integral", async () => { await reset(); const active = await create(); await assert.rejects(() => create(), ConflictError); await authorize(active.id); await new PaymentService().fail(active.id, { failureCode: "DECLINED" }); const retry = await create(); assert.equal(retry.amountInCents, 1000); await new PaymentService().cancel(retry.id); const retryAgain = await create(); assert.notEqual(retry.id, retryAgain.id); });
test("retry gets a new stable provider reference", async () => { await reset(); const first = await create(); const firstStored = await prisma.paymentAttempt.findUnique({ where: { id: first.id } }); await new PaymentService().startProcessing(first.id); await new PaymentService().fail(first.id, { failureCode: "FAILED" }); const second = await create(); assert.notEqual(first.id, second.id); assert.notEqual(firstStored.providerReference, second.providerReference); const provider = new DevPaymentProvider(); const a = await provider.createAttempt({ paymentAttemptId: first.id, orderId: I.o1, method: "PIX", amountInCents: 1000 }); const b = await provider.createAttempt({ paymentAttemptId: first.id, orderId: I.o1, method: "PIX", amountInCents: 1000 }); assert.equal(a.providerReference, b.providerReference); });
test("concurrent creation permits only one active attempt", async () => { await reset(); const results = await Promise.allSettled([create(), create()]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.equal(results.filter((r) => r.status === "rejected").length, 1); assert.equal(await prisma.paymentAttempt.count({ where: { orderId: I.o1, status: { in: ["CREATED", "PROCESSING", "AUTHORIZED"] } } }), 1); });
test("valid state transitions and repeated callbacks are idempotent", async () => { await reset(); const attempt = await create(); await new PaymentService().startProcessing(attempt.id); const stored = await prisma.paymentAttempt.findUnique({ where: { id: attempt.id } }); const authorized = await new PaymentService().authorize(attempt.id, stored.providerReference); const repeated = await new PaymentService().authorize(attempt.id, stored.providerReference); assert.equal(repeated.authorizedAt.getTime(), authorized.authorizedAt.getTime()); await assert.rejects(() => new PaymentService().startProcessing(attempt.id), ConflictError); });
test("full capture confirms the Order once and concurrent captures have one effect", async () => { await reset(); const attempt = await create(); await authorize(attempt.id); const results = await Promise.allSettled([new PaymentService().capture(attempt.id), new PaymentService().capture(attempt.id)]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 2); assert.equal((await prisma.paymentAttempt.findUnique({ where: { id: attempt.id } })).status, "CAPTURED"); assert.equal((await prisma.order.findUnique({ where: { id: I.o1 } })).status, "CONFIRMED"); assert.equal(await prisma.orderStatusHistory.count({ where: { orderId: I.o1, toStatus: "CONFIRMED" } }), 1); await assert.rejects(() => create(), ConflictError); });
test("capture rejects a divergent amount and rollback restores all state", async () => { await reset(); const invalid = await create(); await prisma.paymentAttempt.update({ where: { id: invalid.id }, data: { amountInCents: 999 } }); await authorize(invalid.id); await assert.rejects(() => new PaymentService().capture(invalid.id), ConflictError); await reset(); const attempt = await create(); await authorize(attempt.id); const failing = new PaymentAttemptRepository({ beforeOrderConfirmation: async () => { throw new Error("controlled confirmation failure"); } }); await assert.rejects(() => new PaymentService(failing).capture(attempt.id)); const stored = await prisma.paymentAttempt.findUnique({ where: { id: attempt.id } }); const order = await prisma.order.findUnique({ where: { id: I.o1 } }); assert.equal(stored.status, "AUTHORIZED"); assert.equal(stored.capturedAt, null); assert.equal(order.status, "PENDING_PAYMENT"); assert.equal(order.confirmedAt, null); assert.equal(await prisma.orderStatusHistory.count({ where: { orderId: I.o1 } }), 0); });
test("customer ownership, seller denial, filters and empty collections are enforced", async () => { await reset(); const attempt = await create(); const customerService = new PaymentService(); await assert.rejects(() => customerService.getAttempt(customer2, attempt.id), ObjectNotFoundError); await assert.rejects(() => customerService.listAttempts(seller, I.o1, {}, 1, 20), ForbiddenError); const list = await customerService.listAttempts(customer, I.o1, { status: "CREATED", method: "PIX" }, 1, 1); assert.equal(list.pagination.total, 1); const empty = await customerService.listAttempts(customer, I.o1, { status: "FAILED" }, 1, 20); assert.deepEqual(empty.data, []); });
test("HTTP exposes empty collections and hides legacy refund routes", async () => { await reset(); const listener = await new Promise((resolve) => { const server = app.listen(0, () => resolve(server)); }); const port = listener.address().port; const token = jwt.sign({ sub: I.u1 }, process.env.JWT_SECRET); const headers = { Authorization: `Bearer ${token}` }; assert.equal((await fetch(`http://127.0.0.1:${port}/orders/${I.o1}/payment-attempts`, { headers })).status, 200); assert.equal((await fetch(`http://127.0.0.1:${port}/refund`, { headers })).status, 404); await new Promise((resolve, reject) => listener.close((e) => e ? reject(e) : resolve())); });
