const assert = require("node:assert/strict");
const { after, before, test: nodeTest } = require("node:test");
const { PrismaClient } = require("@prisma/client");
const jwt = require("jsonwebtoken");
const { RefundService } = require("../dist/services/refundService.js");
const { RefundRepository } = require("../dist/repositories/refundRepository.js");
const { DevRefundProvider, RefundProviderDeclinedError, RefundProviderDefinitiveError, RefundProviderUnknownResultError } = require("../dist/providers/refundProvider.js");
const { ConflictError, ObjectNotFoundError, ForbiddenError } = require("../dist/utils/customErrors.js");
const { app } = require("../dist/server.js");
const url = new URL(process.env.TEST_DATABASE_URL || "postgresql://marketplace_dev:marketplace_dev_password@localhost:5433/marketplace_dev");
if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.port !== "5433" || url.pathname !== "/marketplace_dev") throw new Error("Refund tests require localhost:5433/marketplace_dev");
process.env.DATABASE_URL = url.toString(); process.env.JWT_SECRET = "refunds-test-secret";
const prisma = new PrismaClient(); const test = (name, fn) => nodeTest(name, { concurrency: false }, fn);
const I = { u: "93000000-0000-0000-0000-000000000001", c: "93000000-0000-0000-0000-000000000002", au: "93000000-0000-0000-0000-000000000003", su: "93000000-0000-0000-0000-000000000004", o: "93000000-0000-0000-0000-000000000005", pa: "93000000-0000-0000-0000-000000000006" };
const customer = { id: I.u, email: "refund-customer@local.invalid", role: "CUSTOMER" }; const admin = { id: I.au, email: "refund-admin@local.invalid", role: "ADMIN" }; const seller = { id: I.su, email: "refund-seller@local.invalid", role: "SELLER" };
async function clean() { await prisma.$transaction(async (tx) => { await tx.refund.deleteMany({ where: { paymentAttemptId: I.pa } }); await tx.paymentAttempt.deleteMany({ where: { id: I.pa } }); await tx.order.deleteMany({ where: { id: I.o } }); await tx.customerProfile.deleteMany({ where: { id: I.c } }); await tx.user.deleteMany({ where: { id: { in: [I.u, I.au, I.su] } } }); }); }
async function fixtures() { await prisma.user.createMany({ data: [{ id: I.u, name: "Refund Customer", email: customer.email, normalizedEmail: customer.email, password: "test", role: "CUSTOMER" }, { id: I.au, name: "Refund Admin", email: admin.email, normalizedEmail: admin.email, password: "test", role: "ADMIN" }, { id: I.su, name: "Refund Seller", email: seller.email, normalizedEmail: seller.email, password: "test", role: "SELLER" }] }); await prisma.customerProfile.create({ data: { id: I.c, userId: I.u } }); await prisma.order.create({ data: { id: I.o, customerId: I.c, status: "CONFIRMED", subtotalInCents: 10000, totalInCents: 10000, currency: "BRL" } }); await prisma.paymentAttempt.create({ data: { id: I.pa, orderId: I.o, provider: "DEV_SIMULATOR", providerReference: "dev_original_ref", method: "PIX", status: "CAPTURED", amountInCents: 10000, currency: "BRL", capturedAt: new Date("2026-09-01T00:00:00.000Z") } }); }
async function reset() { await prisma.refund.deleteMany({ where: { paymentAttemptId: I.pa } }); }
async function request(amount, user = customer, provider = new DevRefundProvider(), reason = undefined) { return new RefundService(new RefundRepository(), provider).requestRefund(user, I.pa, { amountInCents: amount, reason }); }
before(async () => { await clean(); await fixtures(); }); after(async () => { await clean(); await prisma.$disconnect(); });

test("creates partial and full refunds with integer money and capped aggregate", async () => { await reset(); const a = await request(3000, customer); assert.equal(a.status, "COMPLETED"); assert.equal(a.amountInCents, 3000); assert.equal(a.currency, "BRL"); const b = await request(7000, customer); assert.equal(b.status, "COMPLETED"); await assert.rejects(() => request(1), ConflictError); assert.equal(await prisma.refund.aggregate({ where: { paymentAttemptId: I.pa, status: "COMPLETED" }, _sum: { amountInCents: true } }).then((r) => r._sum.amountInCents), 10000); });
test("rejects invalid amount, protected fields, and non-captured attempts", async () => { await reset(); await assert.rejects(() => request(0), /positive integer/); await assert.rejects(() => request(1.5), /positive integer/); await prisma.paymentAttempt.update({ where: { id: I.pa }, data: { status: "AUTHORIZED" } }); await assert.rejects(() => request(1), ConflictError); await prisma.paymentAttempt.update({ where: { id: I.pa }, data: { status: "CAPTURED" } }); const server = app.listen(0); await new Promise((resolve) => server.once("listening", resolve)); const port = server.address().port; const token = jwt.sign({ sub: I.u }, process.env.JWT_SECRET); const response = await fetch(`http://127.0.0.1:${port}/payment-attempts/${I.pa}/refunds`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ amountInCents: 1, currency: "BRL" }) }); assert.equal(response.status, 400); await new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });
test("REQUESTED/PROCESSING/COMPLETED commit balance while DECLINED/FAILED release it", async () => { await reset(); const requested = await new RefundRepository().createRequested(I.c, I.pa, { amountInCents: 1000 }); assert.equal((await prisma.refund.aggregate({ where: { paymentAttemptId: I.pa, status: { in: ["REQUESTED", "PROCESSING", "COMPLETED"] } }, _sum: { amountInCents: true } }))._sum.amountInCents, 1000); await new RefundRepository().transition(requested.id, "PROCESSING"); await new RefundService(new RefundRepository(), new DevRefundProvider()).provisionRefund(requested.id); await reset(); const declinedError = new RefundProviderDeclinedError("declined", new Error("business rule")); await assert.rejects(() => request(6000, customer, { createRefund: async () => { throw declinedError; } }), (error) => error instanceof RefundProviderDeclinedError && error.cause === declinedError.cause); const declined = await prisma.refund.findFirst({ where: { paymentAttemptId: I.pa } }); assert.equal(declined.status, "DECLINED"); assert.equal(declined.completedAt, null); assert.equal(declined.failedAt, null); const retryAfterDeclined = await request(10000); assert.equal(retryAfterDeclined.status, "COMPLETED"); await reset(); const definitiveError = new RefundProviderDefinitiveError("technical failure", new Error("provider detail")); await assert.rejects(() => request(6000, customer, { createRefund: async () => { throw definitiveError; } }), (error) => error instanceof RefundProviderDefinitiveError && error.cause === definitiveError.cause); const failed = await prisma.refund.findFirst({ where: { paymentAttemptId: I.pa } }); assert.equal(failed.status, "FAILED"); assert.ok(failed.failedAt); const retry = await request(10000); assert.equal(retry.status, "COMPLETED"); });
test("concurrent requests cannot exceed the captured amount", async () => { await reset(); const results = await Promise.allSettled([request(7000), request(7000)]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); assert.equal(results.filter((r) => r.status === "rejected").length, 1); assert.equal(await prisma.refund.aggregate({ where: { paymentAttemptId: I.pa }, _sum: { amountInCents: true } }).then((r) => r._sum.amountInCents), 7000); });
test("provider executes after PROCESSING commits and reference is stable by refund id", async () => { await reset(); let observed; const provider = { createRefund: async (input) => { observed = await prisma.refund.findUnique({ where: { id: input.refundId }, select: { status: true, providerReference: true } }); return new DevRefundProvider().createRefund(input); } }; const result = await request(1000, customer, provider, "  devolução  "); assert.deepEqual(observed, { status: "PROCESSING", providerReference: null }); assert.equal(result.reason, "devolução"); const stored = await prisma.refund.findUnique({ where: { id: result.id } }); const again = await new DevRefundProvider().createRefund({ refundId: result.id, paymentAttemptId: I.pa, paymentProviderReference: "dev_original_ref", amountInCents: 1000, currency: "BRL" }); assert.equal(again.providerReference, stored.providerReference); });
test("unknown and generic errors keep PROCESSING and reconciliation reuses the same refund", async () => { await reset(); const unknown = new RefundProviderUnknownResultError("timeout", new Error("socket closed")); await assert.rejects(() => request(2000, customer, { createRefund: async () => { throw unknown; } }), (error) => error instanceof RefundProviderUnknownResultError && error.cause === unknown.cause); const pending = await prisma.refund.findFirst({ where: { paymentAttemptId: I.pa } }); assert.equal(pending.status, "PROCESSING"); assert.equal(pending.failedAt, null); await assert.rejects(() => request(9000), ConflictError); const recovered = await new RefundService(new RefundRepository(), new DevRefundProvider()).provisionRefund(pending.id); assert.equal(recovered.id, pending.id); assert.equal((await prisma.refund.findUnique({ where: { id: pending.id } })).status, "COMPLETED"); await reset(); const original = new Error("unexpected"); await assert.rejects(() => request(2000, customer, { createRefund: async () => { throw original; } }), (error) => error === original); const generic = await prisma.refund.findFirst({ where: { paymentAttemptId: I.pa } }); assert.equal(generic.status, "PROCESSING"); assert.equal(generic.failedAt, null); });
test("transitions are explicit, idempotent, ownership-scoped and non-destructive", async () => { await reset(); const service = new RefundService(); const requested = await new RefundRepository().createRequested(I.c, I.pa, { amountInCents: 1000 }); const processing = await new RefundRepository().transition(requested.id, "PROCESSING"); const repeated = await new RefundRepository().transition(processing.id, "PROCESSING"); assert.equal(repeated.id, requested.id); await assert.rejects(() => new RefundRepository().transition(requested.id, "REQUESTED"), ConflictError); await assert.rejects(() => service.get(seller, requested.id), ForbiddenError); await assert.rejects(() => service.get({ ...customer, id: "93000000-0000-0000-0000-000000000099" }, requested.id), ForbiddenError); const adminResult = await service.get(admin, requested.id); assert.equal(adminResult.id, requested.id); });
test("filters paginate in the repository and legacy refund mutation routes are unavailable", async () => { await reset(); await request(1000); const service = new RefundService(); const list = await service.list(customer, I.pa, { status: "COMPLETED" }, 1, 1); assert.equal(list.pagination.total, 1); assert.equal(list.data.length, 1); const server = app.listen(0); await new Promise((resolve) => server.once("listening", resolve)); const port = server.address().port; const token = jwt.sign({ sub: I.u }, process.env.JWT_SECRET); const headers = { Authorization: `Bearer ${token}` }; assert.equal((await fetch(`http://127.0.0.1:${port}/refund`, { headers })).status, 404); assert.equal((await fetch(`http://127.0.0.1:${port}/refunds/${list.data[0].id}`, { method: "DELETE", headers })).status, 404); await new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });
