###
# @name createdUser
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name": "Manuel",
    "email": "vmrf2001@hotmail.com",
    "password": "test1234",
    "role": "seller"
}

###
@userId = {{createdUser.response.body.id}}


###
# @name loginUser
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "vmrf2000@hotmail.com",
    "password": "test1234"
}
###
@token = {{loginUser.response.body.token}}

###
GET http://localhost:8000/users/057fd440-3a11-4e48-8152-1c7dbbfdef55
Authorization: Bearer {{token}}

###
PUT http://localhost:8000/users/057fd440-3a11-4e48-8152-1c7dbbfdef55
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Pablo Vegetti",
    "email": "pablo.vegetti@vasco.com"
}

###
DELETE http://localhost:8000/users/{{userId}}
Authorization: Bearer {{token}}

#### CUSTOMER

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name": "Nuno Moreira",
    "email": "nuno.moreira@vasco.com",
    "password": "test1234",
    "role": "customer"
}

###
# @name customerLogin
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "nuno.moreira@vasco.com",
    "password": "test1234"
}

###
@customerToken = {{customerLogin.response.body.token}}

### 
POST http://localhost:8000/customers/profile
Authorization: Bearer {{customerToken}}
Content-Type: application/json

{
    "address": "São Januário, RJ",
    "phone": "+55 11 98765-4321"
}

#### SELLER

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name": "Dimitry Payet",
    "email": "dimitry.payet@vasco.com",
    "password": "teste1234",
    "role": "seller"
}

###
# @name sellerLogin
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "dimitry.payet@vasco.com",
    "password": "teste1234"
}

###
@sellerToken = {{sellerLogin.response.body.token}}

###
POST http://localhost:8000/sellers/profile
Authorization: Bearer {{sellerToken}}
Content-Type: application/json

{
    "storeName": "Loja do gigante",
    "description": "Um lugar onde você encontrará todos os produtos oficiais do gigante da colina nos melhores preços"
}

#### ADMIN 
###
# @name adminLogin
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "vmrf2000@hotmail.com",
    "password": "test1234"
}

###
@adminToken = {{adminLogin.response.body.token}}

###
GET http://localhost:8000/customers/
Authorization: Bearer {{adminToken}}

###
GET http://localhost:8000/sellers/
Authorization: Bearer {{adminToken}}

###
PUT http://localhost:8000/customers/profile/0f2bc54d-5b6d-424f-b3da-
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "phone": "+55 11 12345-6789"
}

###
DELETE http://localhost:8000/customers/profile/12123312314
Authorization: Bearer {{customerToken}}