###
# @name createdUser
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name": "Manuel",
    "email": "vmrf2001@hotmail.com",
    "password": "test1234",
    "role": "seller"
}

###
@userId = {{createdUser.response.body.id}}


###
# @name loginUser
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "vmrf2000@hotmail.com",
    "password": "test1234"
}
###
@token = {{loginUser.response.body.token}}

###
GET http://localhost:8000/users/057fd440-3a11-4e48-8152-1c7dbbfdef55
Authorization: Bearer {{token}}

###
PUT http://localhost:8000/users/057fd440-3a11-4e48-8152-1c7dbbfdef55
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Pablo Vegetti",
    "email": "pablo.vegetti@vasco.com"
}

###
DELETE http://localhost:8000/users/{{userId}}
Authorization: Bearer {{token}}

###
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "name": "Nuno Moreira",
    "email": "nuno.moreira@vasco.com",
    "password": "test1234",
    "role": "customer"
}

###
# @name customerLogin
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "nuno.moreira@vasco.com",
    "password": "test1234"
}

###
@customerToken = {{customerLogin.response.body.token}}

### 
POST http://localhost:8000/customers/profile
Authorization: Bearer {{customerToken}}
Content-Type: application/json

{
    "address": "São Januário, RJ",
    "phone": "+55 11 98765-4321"
}